port=10000
root=/var/packages/webmin/target/webmin
mimetypes=/var/packages/webmin/target/webmin/mime.types
addtype_cgi=internal/cgi
realm=Webmin Server
logfile=/var/packages/webmin/target/var/miniserv.log
errorlog=/var/packages/webmin/target/var/miniserv.error
pidfile=/var/packages/webmin/target/var/miniserv.pid
ssl=1
no_ssl2=1
no_ssl3=1
ssl_honorcipherorder=1
userfile=/var/packages/webmin/target/etc/miniserv.users
keyfile=/var/packages/webmin/target/etc/miniserv.pem
passwd_file=/etc/shadow
passwd_uindex=0
passwd_pindex=1
passwd_cindex=2
passwd_mindex=4
passwd_mode=0
preroot=Webmin
logout=/var/packages/webmin/target/webmin/session_login.cgi
listen=10000
bind=0.0.0.0
